#!/usr/bin/env bash

#5/3
echo "5/3 = $((5/3))"

echo "5/3 =" && echo "scale=2; 5/3" | bc 
#5+3
echo "5+3 = $((5+3))"
#5%3
echo "5%3 = $((5%3))"
#5-3
echo "5-3 = $((5-3))"

pi=3.141592
radius=2
area=$(echo "scale=2; $pi*$radius^2" | bc
)

echo "circle area: $area"

